import React from "react";

const CostDrawer = ({ isOpen, onClose, data, theme }) => {
  if (!data) return null;
  const isDark = theme === "dark";

  return (
    <>
      {/* Backdrop */}
      <div
        onClick={onClose}
        className={`fixed inset-0 z-[60] transition-opacity ${
          isOpen ? "opacity-100 pointer-events-auto" : "opacity-0 pointer-events-none"
        } bg-black/40 backdrop-blur-sm`}
      />

      {/* Drawer */}
      <aside
        className={`fixed top-0 right-0 z-[70] h-full w-full sm:w-[420px]
          transform transition-transform duration-300
          ${isOpen ? "translate-x-0" : "translate-x-full"}
          ${isDark ? "bg-[#0c0c0e] text-white border-white/10" : "bg-white text-zinc-900 border-zinc-200"}
          border-l shadow-2xl flex flex-col`}
      >
        {/* Header */}
        <div className={`px-6 py-5 border-b flex justify-between items-center
          ${isDark ? "border-white/10 bg-white/[0.03]" : "border-zinc-200 bg-zinc-50"}`}>
          <h3 className={`text-xs font-bold tracking-widest uppercase ${isDark ? "text-indigo-400" : "text-indigo-600"}`}>
            Infracost Analytics
          </h3>
          <button onClick={onClose} className="text-xl opacity-60 hover:opacity-100">×</button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 space-y-8">
          
          {/* Total */}
          <div className={`rounded-2xl p-6 text-center border
            ${isDark ? "bg-indigo-500/10 border-indigo-500/20" : "bg-indigo-50 border-indigo-200"}`}>
            <p className="text-[10px] tracking-[0.2em] uppercase mb-2 opacity-70">
              Estimated Monthly Total
            </p>
            <p className="text-5xl font-black">
              <span className="text-2xl opacity-50">$</span>{data.total}
            </p>
          </div>

          {/* Resources */}
          {data.resources.map((res, idx) => (
            <div key={idx} className="space-y-3">
              <h4 className={`text-sm font-semibold ${isDark ? "text-indigo-300" : "text-indigo-700"}`}>
                {res.name}
              </h4>

              {res.components.map((comp, i) => (
                <div
                  key={i}
                  className={`flex justify-between items-start p-4 rounded-xl border
                    ${isDark ? "bg-white/[0.03] border-white/10" : "bg-zinc-50 border-zinc-200"}`}
                >
                  <div>
                    <p className="text-sm font-medium">{comp.name}</p>
                    <p className="text-[11px] opacity-60">
                      {comp.quantity} {comp.unit}
                    </p>
                  </div>
                  <p className="font-mono font-bold">${comp.cost}</p>
                </div>
              ))}
            </div>
          ))}

          {/* Footer */}
          <p className="text-[10px] italic text-center opacity-60">
            Generated by Infracost v{data.version}. Costs are estimates only.
          </p>
        </div>
      </aside>
    </>
  );
};

export default CostDrawer;



/* costData = {
  total: "9.09",
  currency: "USD",
  resources: [
    {
      name: "aws_instance.linux_ec2",
      cost: "9.09",
      components: [
        {
          name: "Instance usage (Linux/UNIX, on-demand, t3.micro)",
          cost: "8.18",
          unit: "hours",
          quantity: 730
        },
        {
          name: "Storage (gp2)",
          cost: "0.91",
          unit: "GB",
          quantity: 8
        }
      ]
    }
  ],
  source: "infracost-cli",
  version: "0.10.43"
}
*/